### PR TITLE
[FIX]project_ux: performance in projects

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/project/pull/124).

**Comment by ced-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @ced-adhoc. I'm afraid I can't do that.

**Comment by ced-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @ced-adhoc: I must know your email before you can review PRs. Please contact an administrator.

**Comment by ced-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
