### PR TITLE
[MIG] project_ux: Migration to 15.0

### PR DESCRIPTION
**Pull request by pablohmontenegro**
Task: 25547

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/project/pull/102).

**Comment by jjscarafia** [comment]
@roboadhoc r+ override=ci/oba_without_tests

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jjscarafia, you may want to rebuild or fix this PR as it has failed CI.

**Pull request merged**
