### PR TITLE
[FW][FIX] project_ux: project_ux does not depend on hr_timesheet

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/project#105

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/project/pull/106).

**Comment by fw-bot-adhoc** [comment]
Ping @vib-adhoc, @Bruno-Zanotti cherrypicking of pull request ingadhoc/project#105 failed.

stdout:
```
CONFLICT (modify/delete): project_ux/views/project_portal_templates.xml deleted in HEAD and modified in 9005080... [FIX] project_ux: project_ux does not depend on hr_timesheet. Version 9005080... [FIX] project_ux: project_ux does not depend on hr_timesheet of project_ux/views/project_portal_templates.xml left in tree.
Auto-merging project_ux/__manifest__.py
CONFLICT (content): Merge conflict in project_ux/__manifest__.py

```

stderr:
```
13:37:26.420182 git.c:439               trace: built-in: git cherry-pick 90050804239b537758dcd6a047dca7cf57da5662
error: could not apply 9005080... [FIX] project_ux: project_ux does not depend on hr_timesheet
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by bruno-zanotti** [comment]
@roboadhoc override=ci/oba_without_tests r+

**Comment by roboadhoc** [comment]
@Bruno-Zanotti, you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti. You are not allowed to override this status.

**Comment by vib-adhoc** [comment]
@nicomacr Hola Nico, cómo podemos hacer para mezclar esto? Podés hacerlo vos o hay algo de mi lado que tenga que hacer?

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Pull request closed without merging**
