### PR TITLE
[MIG] project_stage: Migration to 15.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/project/pull/101).

**Review by PabloPaezSheridan — APPROVED** [review]

**Comment by PabloPaezSheridan** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@PabloPaezSheridan, you may want to rebuild or fix this PR as it has failed CI.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Pull request closed without merging**
