### PR TITLE
[ADD] extend filterby fuctions

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/project/pull/108).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/project#109

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/project#109

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/project#109

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/project#109

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/project#109

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/project#109

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/project#109

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/project#109

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/project#109

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/project#109

**Pull request closed without merging**
