### PR TITLE
[MIG] project_ux: Migration to 18.0

### PR DESCRIPTION
**Pull request by mas-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/project/pull/128).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by jcadhoc** [comment]
@roboadhoc rebase--ff

**Comment by jcadhoc** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
@mas-adhoc @jcadhoc unable to stage: commits with multiple parents (2e03fc8c93663c87cf83fd13c4f66703f5757f27) can not be rebased, either fix the branch to remove merges or merge without rebasing

**Pull request closed without merging**
